import os
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    HRFlowable,
    Image,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

def add_footer(canvas, doc):
    canvas.saveState()
    canvas.setFont('Helvetica', 7)
    canvas.setFillColor(colors.HexColor("#A3A3A3"))
    page_num = canvas.getPageNumber()
    footer_text = f"GENERATED BY DEEPTRACE v1.0   |   CONFIDENTIAL   |   PAGE {page_num}"
    canvas.drawCentredString(A4[0] / 2.0, 1.0 * cm, footer_text)
    canvas.setStrokeColor(colors.HexColor("#E5E5E5"))
    canvas.setLineWidth(0.5)
    canvas.line(2 * cm, 1.5 * cm, A4[0] - 2 * cm, 1.5 * cm)
    canvas.restoreState()

def generate_pdf_report(analysis: dict, output_dir: str) -> str:
    """Generate a sleek, minimal PDF forensic report and return the file path."""

    aid = analysis.get("id", "unknown")
    pdf_path = os.path.join(output_dir, f"{aid}_report.pdf")

    doc = SimpleDocTemplate(
        pdf_path,
        pagesize=A4,
        topMargin=1.5 * cm,
        bottomMargin=2.0 * cm,
        leftMargin=2 * cm,
        rightMargin=2 * cm,
    )

    story = []

    # ── custom styles ────────────────────────────────────────────────
    body_style = ParagraphStyle(
        "Body", fontName="Helvetica", fontSize=9, leading=14, textColor=colors.HexColor("#404040")
    )
    
    heading_style = ParagraphStyle(
        "Heading", fontName="Helvetica-Bold", fontSize=9, leading=14, 
        textColor=colors.HexColor("#737373"), spaceBefore=24, spaceAfter=12
    )

    # ── header ───────────────────────────────────────────────────────
    header_data = [
        [
            Paragraph("<b>DEEPTRACE</b><br/><font color='#737373' size='8'>FORENSIC ANALYSIS REPORT</font>", body_style),
            Paragraph(f"<font color='#737373' size='7'>REPORT ID</font><br/><b>DT-{str(aid).upper()}</b>", ParagraphStyle("", parent=body_style, alignment=2)),
            Paragraph(f"<font color='#737373' size='7'>GENERATED</font><br/><b>{datetime.now().strftime('%b %d, %Y')}</b>", ParagraphStyle("", parent=body_style, alignment=2))
        ]
    ]
    ht = Table(header_data, colWidths=[9*cm, 4*cm, 4*cm])
    ht.setStyle(TableStyle([
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
    ]))
    story.append(ht)
    story.append(Spacer(1, 10))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#E5E5E5")))

    # ── 1. executive summary ─────────────────────────────────────────
    verdict = analysis.get("verdict", "UNKNOWN").upper()
    conf = analysis.get("confidence", 0)
    risk = analysis.get("risk_level", "UNKNOWN").upper()
    is_real = verdict == "AUTHENTIC"
    
    if verdict == "AUTHENTIC":
        v_color = "#22C55E"
    elif verdict == "SUSPICIOUS":
        v_color = "#F59E0B"
    else:
        v_color = "#EF4444"
    
    story.append(Paragraph("OVERALL ASSESSMENT", heading_style))
    
    exec_data = [
        [
            Paragraph(f"<font color='{v_color}' size='22'><b>{verdict}</b></font><br/><br/><font color='#737373' size='7'>RISK LEVEL:</font> <font color='{v_color}'><b>{risk}</b></font>", body_style),
            Paragraph(f"<font size='26'><b>{conf}%</b></font><br/><br/><font color='#737373' size='7'>CONFIDENCE SCORE</font>", ParagraphStyle("", parent=body_style, alignment=2))
        ]
    ]
    
    et = Table(exec_data, colWidths=[11*cm, 6*cm])
    et.setStyle(TableStyle([
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
    ]))
    story.append(et)
    story.append(Spacer(1, 15))
    
    story.append(Paragraph(
        f"DeepTrace forensic analysis indicates <b>{'no significant' if is_real else 'significant'}</b> manipulation patterns in the provided media. "
        f"The model is {conf}% confident in this classification based on spatial artifacts, error level variance, and face region analysis.",
        body_style
    ))

    # ── 2. image evidence ────────────────────────────────────────────
    story.append(Paragraph("VISUAL EVIDENCE", heading_style))

    evidence_images = [
        ("ORIGINAL IMAGE", "original", "original"), 
        ("GRAD-CAM SALIENCY", "heatmap", "heatmap"),
        ("FACE DETECTION", "face_detection", "face"),
        ("ERROR LEVEL ANALYSIS", "ela", "ela")
    ]
    
    import requests
    from io import BytesIO

    img_cells = []
    images_dict = analysis.get("images", {})
    
    for label, dict_key, file_key in evidence_images:
        src = images_dict.get(dict_key)
        
        # 1. Check if we have a valid HTTP Cloudinary URL
        if src and src.startswith("http"):
            try:
                res = requests.get(src, timeout=5)
                if res.status_code == 200:
                    img_cells.append((label, BytesIO(res.content)))
                    continue
            except Exception:
                pass # fallback to local
                
        # 2. Fallback to local disk path
        fpath = os.path.join(output_dir, f"{aid}_{file_key}.jpg")
        if os.path.exists(fpath):
            img_cells.append((label, fpath))

    if img_cells:
        rows = [img_cells[i:i+2] for i in range(0, len(img_cells), 2)]
        for row in rows:
            imgs_row = []
            labels_row = []
            for label, img_src in row:
                imgs_row.append(Image(img_src, width=6.5 * cm, height=5.5 * cm, kind='proportional'))
                labels_row.append(Paragraph(f"<font color='#737373' size='8'><b>{label}</b></font>", ParagraphStyle("", parent=body_style, alignment=1)))
            
            while len(imgs_row) < 2:
                imgs_row.append(Paragraph("<font color='#A3A3A3'><i>(Not available)</i></font>", ParagraphStyle("", parent=body_style, alignment=1)))
                labels_row.append(Paragraph("", body_style))

            t = Table([imgs_row, labels_row], colWidths=[8 * cm, 8 * cm])
            t.setStyle(TableStyle([
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("TOPPADDING", (0, 1), (-1, 1), 6),
                ("BOTTOMPADDING", (0, 1), (-1, 1), 12),
            ]))
            story.append(t)
    else:
        story.append(Paragraph("<i>No visual evidence generated.</i>", body_style))

    # ── 3. key forensic findings ─────────────────────────────────────
    findings = analysis.get("findings", [])
    if findings:
        story.append(Paragraph("KEY FORENSIC FINDINGS", heading_style))
        for finding in findings:
            story.append(Paragraph(f"<font color='#3B82F6'>▪</font>  {finding}", body_style))
            story.append(Spacer(1, 4))
        story.append(Spacer(1, 8))

    # ── 4. metrics and metadata ──────────────────────────────────────
    def make_clean_table(data, col_widths):
        t = Table(data, colWidths=col_widths)
        t.setStyle(TableStyle([
            ('FONTNAME', (0,0), (0,-1), 'Helvetica-Bold'),
            ('TEXTCOLOR', (0,0), (0,-1), colors.HexColor("#737373")),
            ('FONTSIZE', (0,0), (-1,-1), 8),
            ('BOTTOMPADDING', (0,0), (-1,-1), 8),
            ('TOPPADDING', (0,0), (-1,-1), 8),
            ('LINEBELOW', (0,0), (-1,-2), 0.5, colors.HexColor("#E5E5E5")),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ]))
        return t

    story.append(Paragraph("ANALYSIS METRICS", heading_style))
    fd = analysis.get("face_detection", {})
    ela = analysis.get("ela", {})
    scores = analysis.get("scores", {})
    
    metrics_data = [
        ["FACES DETECTED", str(fd.get("count", 0))],
        ["MTCNN CONFIDENCE", f'{fd.get("confidence", 0)}%'],
        ["FACE MANIPULATION", f'{scores.get("face_manipulation", 0)}%'],
        ["COMPRESSION ANOMALY", f'{scores.get("compression_anomaly", 0)}%'],
        ["METADATA INTEGRITY", f'{scores.get("metadata_integrity", 0)}%'],
        ["ELA VARIANCE", f'{ela.get("variance_score", 0)}% — {ela.get("description", "N/A")}'],
    ]
    story.append(make_clean_table(metrics_data, [5.5*cm, 11.5*cm]))
    
    story.append(Paragraph("FILE METADATA", heading_style))
    meta = analysis.get("metadata", {})
    meta_data = [
        ["FILE NAME", meta.get("file_name", "—")],
        ["FILE SIZE", meta.get("file_size", "—")],
        ["DIMENSIONS", meta.get("dimensions", "—")],
        ["FORMAT", meta.get("format", "—")],
        ["SOFTWARE", meta.get("software", "N/A")],
        ["GPS DATA", meta.get("gps_data", "—")],
    ]
    story.append(make_clean_table(meta_data, [5.5*cm, 11.5*cm]))

    # ── 4. recommendations ───────────────────────────────────────────
    story.append(Paragraph("RECOMMENDATIONS", heading_style))
    if is_real:
        recs = [
            "The image appears genuine and passes standard verification checks.",
            "No significant manipulation artifacts were detected.",
            "Retain this report and original file hash for audit records.",
        ]
    else:
        recs = [
            "Do not use this media as verified evidence without independent corroboration.",
            "Flag the source for potential disinformation distribution.",
            "Retain this report and original file hash for audit records.",
        ]
        
    for r in recs:
        story.append(Paragraph(f"<font color='#737373'>•</font>  {r}", body_style))
        story.append(Spacer(1, 6))

    doc.build(story, onFirstPage=add_footer, onLaterPages=add_footer)
    return pdf_path
